### ISSUE TITLE
Не запускается на win7 x64

### ISSUE THREAD

**Issue by pilot114** [mast3rm1nd/Jarvis#1]
при попытке запустить на  win7 x64 вылетает.

Описание:
  Stopped working

Сигнатура проблемы:
  Имя события проблемы:   CLR20r3
  Сигнатура проблемы 01:   jarvena.exe
  Сигнатура проблемы 02:   1.0.0.0
  Сигнатура проблемы 03:   571677f0
  Сигнатура проблемы 04:   PresentationFramework
  Сигнатура проблемы 05:   3.0.0.0
  Сигнатура проблемы 06:   4ca2e335
  Сигнатура проблемы 07:   625d
  Сигнатура проблемы 08:   e1
  Сигнатура проблемы 09:   System.Windows.Markup.XamlParse
  Версия ОС:    6.1.7601.2.1.0.256.1
  Код языка:    1049

Speech SDK и прочие либы установлены

**Comment by mast3rm1nd** [comment]
Попробуй поставить .NET Framework 3.5

**Comment by pilot114** [comment]
Ничего не изменилось

**Comment by mast3rm1nd** [comment]
конфиг должен быть в папке с прогой.
в системе должны быть установлены устройства по-умолчанию для записи и для воспроизведения звука.
